### ISSUE TITLE
Not compatible with the version of your running IDE (IntelliJ IDEA 2024.2)

### ISSUE THREAD

**Issue by hafnerkai** [LeonDevLifeLog/gitea-idea-plugin#100]
Unfortunately, I can't install the plugin because JetBrains recently updated the versions of their applications, making the plugin no longer installable.

Please adjust the plugin so that it can be used with the new version.

**Comment by LeonDevLifeLog** [comment]
This is a major update, wait for me.

**Comment by LeonDevLifeLog** [comment]
idea Plugin SDK 1.x -> 2.x
