### ISSUE TITLE
Using shortcut with Gitea panel

### ISSUE THREAD

**Issue by Rapid0s** [LeonDevLifeLog/gitea-idea-plugin#24]
If you assign a shortcut to "Tool Windows | Gitea" and open the panel using the shortcut I would expect pressing again the shortcut and while the panel is visible to hide the panel.

PhpStorm 2023.2.2
Build #PS-232.9921.55, built on September 15, 2023 - Windows10

**Comment by LeonDevLifeLog** [comment]
related resources 
* https://intellij-support.jetbrains.com/hc/en-us/community/posts/206314449-How-can-I-get-my-shortcuts-toggle-panels

**Comment by LeonDevLifeLog** [comment]
you can cloes all tool window by "Main Menu > Window Active Tool Window > Hide All Too Windows" or shortcut

https://intellij-support.jetbrains.com/hc/en-us/community/posts/206832805/comments/206303935
