### ISSUE TITLE
Gitea instance URL

### ISSUE THREAD

**Issue by majlantalik** [LeonDevLifeLog/gitea-idea-plugin#39]
If the gitea instance is not located at the root level of an URL, the authentication (and probably all other fetatures) do not work.

Example:
https://foo.bar.com/ -> this probably works (cannot really test, but I assume it does)
https://foo.bar.com/gitea/ -> this does not work.

I believe the problem is that the path after first "/" is ignored, e.g. when I click on "Get Access Token" button, a browser opens with the address "https://foo.bar.com/user/settings/applications".

IntelliJ IDEA 2023.2.5 (Ultimate Edition)
Build #IU-232.10227.8, built on November 9, 2023

**Comment by LeonDevLifeLog** [comment]
Thank you for reporting this issue, I will fix it after trying it

**Comment by Iatbzh** [comment]
I have the same problem
