### ISSUE TITLE
Update for IntelliJ IDEA 2024.1

### ISSUE THREAD

**Issue by TweakM** [LeonDevLifeLog/gitea-idea-plugin#69]
It would be really nice if the plugin could be updated to be compatible with the 2024.1 version if IDEA. After updating, the following error message is displayed:
Plugin 'Gitea' (version '0.3.3') is not compatible with the current version of the IDE, because it requires build 233.* or older but the current build is IU-241.14494.240

This plugin has been really useful, thank you for making this possible!

**Comment by TweakM** [comment]
Thanks for suggesting this workaround. FYI: after running the build there was no build/distributions directory, but I found a build/lib directory containing the gitea-0.3.3.1.jar, which could be manually installed. 
@LeonDevLifeLog : Would you be able to tell if this workaround is also a structural solution (i.e. the pluginUntilBuild can safely be set to 241)?

**Comment by LeonDevLifeLog** [comment]
i will update this plugin soon

**Comment by TweakM** [comment]
Thank you!
